### ISSUE TITLE
Is this project dead ?

### ISSUE THREAD

**Issue by sbacquet** [Horusiath/Akkling#172]
@Horusiath @object 
For several months, no answer to issues, no comment, no PR merged.

Is this project abandoned ?
That would be a significant loss.

**Comment by object** [comment]
No it is absolutely not. The project is alive and we had a release related to Akka 1.5 that had a breaking change.
Having said that, now when I am the main maintainer, I need to better understand how the library can be developed in the future. Right now I just ensure it works fine with latest Akka.NET releases. And it does. If you have any requests, please speak up.
Cheers.

**Comment by sbacquet** [comment]
I'm so glad to read that !

I'm a big fan of Akkling, and use it a lot even in corporate projects.
However there is a nasty bug I had to work around : #159  

Finally I managed to fix it with a simple change : https://github.com/Horusiath/Akkling/pull/171

Could you please consider merging it in an official release if it sounds good to you ?
Thanks in advance

**Comment by object** [comment]
Sorry I overlooked this PR. I will take a look and merge it if it works as intended.

**Comment by object** [comment]
Hi again, I just merged your PR. Will release new package soon (first as prerelease to test with my other projects).

**Comment by object** [comment]
Hi again, I just merged your PR. Will release new package soon (first as prerelease to test with my other projects).

**Comment by sbacquet** [comment]
Thanks a lot Vagif !

**Comment by object** [comment]
@sbacquet FYI: I just released version 0.15.0 with your PR applied.

**Comment by sbacquet** [comment]
Hi @object , thanks again for merging the PR, it helped a lot.
Unfortunately, some issues remain, and now I understand why. 
I'm preparing a new PR to solve them for good, hopefully.
